### ISSUE TITLE
[EPIC] GPS blending issues

### ISSUE THREAD

**Issue by bresch** [PX4/Firmware#14252]
Summary of the current GPS blending issues:

- [ ] EKF2: GPS blending seems to give wrong output for fast changing position meas : https://github.com/PX4/Firmware/issues/14251
- [ ] EKF does not switch to secondary GPS if main fails: https://github.com/PX4/Firmware/issues/14223
- [ ] @DanielePettenuzzo Please link your issue with the height sources

GPS blending logic:
https://github.com/PX4/Firmware/blob/f90d3671c01d45d562a57ae3546ce35011aab199/src/modules/ekf2/ekf2_main.cpp#L945-L1016

FYI @CarlOlsson  @priseborough  @DanielePettenuzzo
