### ISSUE TITLE
Fixed wing master test todo list

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3260]
- [x] in auto mode there is no idle throttle for takeoff. If takeoff has been detected once (but went back to landed) then the plane will always throttle up 100% even if the status is landed again
- [x] discuss option to allow (maybe parameter) full throttle on takeoff even if takeoff hasn't been detected yet. From user experience the time needed for the takeoff detector to trigger is too long. The plane looses too much speed, especially when launching wings over the head. Maybe idle speed could be a parameter which defaults to a small value but which can be set to 100 %
- [x] we need to implement the correct waypoint projection for position control. It seemed that in position control the plane tended to wiggle around more than during a mission

**Comment by tumbili** [comment]
Tested on latest master 24.11.2015
- manual
- altclt (also launching in this mode)
- posctl
- mission
- stabilized
- autotakeoff (launch)

New landing detector has been tested and works fine.

**Comment by LorenzMeier** [comment]
Nice work!

**Comment by LorenzMeier** [comment]
@tumbili Are all three of these still open? Did you fix the waypoint projection?

**Comment by LorenzMeier** [comment]
3) Is fixed here: https://github.com/PX4/Firmware/pull/3491

**Comment by tumbili** [comment]
The second point was fixed by improving the landed detector. Closing!
